###
GET http://localhost:3000/users HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/users/604967b48950f35ed853fc62 HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name":"Aliny",
    "cpf": "243423"
}

###
PATCH http://localhost:3000/users/604967b48950f35ed853fc64 HTTP/1.1
content-type: application/json

{
    "name":"Carlos"
}

###
DELETE  http://localhost:3000/users/604967b48950f35ed853fc65 HTTP/1.1
content-type: application/json